### PR TITLE
feat: expand edit types

### PR DESCRIPTION
**Pull request by BobBorges**
Add:
```
- [ ] Incorrect --> Correct
- [ ] Correct --> Incorrect
- [ ] Incorrect --> Incorrect
```

### CODE REVIEW

**Comment by ninpnin** [comment]
I would add this as a flag

**Comment by BobBorges** [comment]
> I would add this as a flag

done

**Comment by MansMeg** [comment]
@ninpnin can you review and accept this?

**Review by ninpnin — APPROVED** [review]

**Comment by MansMeg** [comment]
I think you need to merge @ninpnin

**Pull request merged**
